sudo: required
language: java
services:
  - docker
jdk:
  - oraclejdk8
before_script: 
  - cd complete
script:
  # - test/run.sh
  - mvn package docker:build
  - docker push ned13/gs-spring-boot-docker

